version: 2

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    gh-actions:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
