title: Exploring the universe

author:
  name: Nelu Snegur
  email: contact@pulsarplanet.com
  username: nelusnegur

description: >-
  Exploring the universe

url: "https://pulsarplanet.com"

date_format: "%b %-d, %Y"

permalink: /blog/:categories/:title/

markdown: kramdown

plugins:
  - jekyll-feed
